import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { BarChart, ResponsiveContainer, CartesianGrid, XAxis, YAxis, Tooltip, Legend, Bar } from 'recharts'

const inter = Inter({ subsets: ['latin'] })

interface LossData {
  country: string,
  equipment_type: string,
  destroyed: string,
  abandoned: string,
  captured: string,
  damaged: string,
  type_total: string
}

export default function Home({ data }: { data: Array<LossData> }) {
  const russiaInfo = data.slice(0, Math.ceil(data.length / 2))
  const ukraineInfo = data.slice(Math.ceil(data.length / 2))

  function generateLossText(data: LossData) {
    if(data.equipment_type === 'All Types') {
        return (
          <div className='data-container' key={data.type_total}>
            <h2>{`Total Number of Equipment Lost`}: <span>{data.type_total}</span></h2>
            <p>Out of which:</p>
            <p>Destroyed: <span>{data.destroyed}</span></p>
            <p>Damaged: <span>{data.damaged}</span></p>
            <p>Captured: <span>{data.captured}</span></p>
            <p>Abandoned: <span>{data.abandoned}</span></p>
          </div>
        )
    }
  }

  function generateLossCharts(russia: Array<LossData>, ukraine: Array<LossData>) {
    let elementArray: Array<any> = []

    russia.forEach((val) => {
      if(val.equipment_type === 'Reconnaissance Unmanned Aerial Vehicles') {
        val.equipment_type = 'Unmanned Aerial Vehicles'
      }
      else if(val.equipment_type === 'Radars') {
        val.equipment_type = 'Radars And Communications Equipment'
      }
    })

    let unifiedArray = [...russia, ...ukraine ]
    unifiedArray.sort((a, b) => a.equipment_type > b.equipment_type ? 1 : -1)

    for(let i = 0; i <= unifiedArray.length / 2; i+=2) {
      const tempArray: Array<LossData> = [unifiedArray[i], unifiedArray[i+1]]
      elementArray.push(
        <ResponsiveContainer height={"100%"} width={"100%"}>
        <BarChart 
        data={tempArray}
        margin={{
          top: 5,
          right: 30,
          left: 20,
          bottom: 5,
        }}
        >
          <CartesianGrid />
          <XAxis dataKey={"country"}/>
          <YAxis />
          <Tooltip/>
          <Legend />
          <Bar dataKey={"destroyed"} fill='red'/>
        </BarChart>
      </ResponsiveContainer>
      )
    }

    return elementArray
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section className="text-data">
          <h1>Number of Russian Equipment Losses</h1>
          {russiaInfo.map((obj) => {
            return (
              generateLossText(obj)
            )
          })}
          <h1>Number of Ukrainian Equipment Losses</h1>
          {ukraineInfo.map((obj) => {
            return (
              generateLossText(obj)
            )
          })}
        </section>
        <section className='chart-data'>
          <h1>Comparison of Ukrainian and Russian Losses by Type</h1>
          <div className={styles.chart_container}>
          {generateLossCharts(russiaInfo, ukraineInfo)}
          </div>
        </section>
      </main>
    </>
  )
}

export async function getStaticProps() {
  const res = await fetch('http://localhost:3000/api/data')
  const data = await res.json()
  return {
    props: {
      data: data
    }
  }
}