import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

interface LossData {
  country: string,
  equipment_type: string,
  destroyed: string,
  abandoned: string,
  captured: string,
  damaged: string,
  type_total: string
}

export default function Home({ data }: { data: Array<LossData> }) {
  const russiaInfo = data.slice(0, Math.ceil(data.length / 2))
  const ukraineInfo = data.slice(Math.ceil(data.length / 2))

  function generateLossDisplay(data: LossData) {
    switch(data.equipment_type) {
      case 'All Types':
        return (
          <div className='data-container' key={data.type_total}>
            <h2>{`Total Number of Equipment Lost`}: <span>{data.type_total}</span></h2>
            <p>Out of which:</p>
            <p>Destroyed: <span>{data.destroyed}</span></p>
            <p>Damaged: <span>{data.damaged}</span></p>
            <p>Captured: <span>{data.captured}</span></p>
            <p>Abandoned: <span>{data.abandoned}</span></p>
          </div>
        )
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section className="text-data">
          <h1>Number of Russian Equipment Losses</h1>
          {russiaInfo.map((obj) => {
            return (
              generateLossDisplay(obj)
            )
          })}
          <h1>Number of Ukrainian Equipment Losses</h1>
          {ukraineInfo.map((obj) => {
            return (
              generateLossDisplay(obj)
            )
          })}
        </section>
      </main>
    </>
  )
}

export async function getStaticProps() {
  const res = await fetch('http://localhost:3000/api/data')
  const data = await res.json()
  return {
    props: {
      data: data
    }
  }
}